.class public Lcom/evernote/edam/notestore/NoteStore;
.super Ljava/lang/Object;
.source "NoteStore.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/evernote/edam/notestore/NoteStore$1;,
        Lcom/evernote/edam/notestore/NoteStore$authenticateToSharedNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$authenticateToSharedNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$stopSharingNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$stopSharingNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$shareNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$shareNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$emailNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$emailNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$getSharedNotebookByAuth_result;,
        Lcom/evernote/edam/notestore/NoteStore$getSharedNotebookByAuth_args;,
        Lcom/evernote/edam/notestore/NoteStore$authenticateToSharedNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$authenticateToSharedNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeLinkedNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeLinkedNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$listLinkedNotebooks_result;,
        Lcom/evernote/edam/notestore/NoteStore$listLinkedNotebooks_args;,
        Lcom/evernote/edam/notestore/NoteStore$updateLinkedNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$updateLinkedNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$createLinkedNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$createLinkedNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeSharedNotebooks_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeSharedNotebooks_args;,
        Lcom/evernote/edam/notestore/NoteStore$listSharedNotebooks_result;,
        Lcom/evernote/edam/notestore/NoteStore$listSharedNotebooks_args;,
        Lcom/evernote/edam/notestore/NoteStore$sendMessageToSharedNotebookMembers_result;,
        Lcom/evernote/edam/notestore/NoteStore$sendMessageToSharedNotebookMembers_args;,
        Lcom/evernote/edam/notestore/NoteStore$createSharedNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$createSharedNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$getPublicNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$getPublicNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$getRandomAd_result;,
        Lcom/evernote/edam/notestore/NoteStore$getRandomAd_args;,
        Lcom/evernote/edam/notestore/NoteStore$getAds_result;,
        Lcom/evernote/edam/notestore/NoteStore$getAds_args;,
        Lcom/evernote/edam/notestore/NoteStore$getAccountSize_result;,
        Lcom/evernote/edam/notestore/NoteStore$getAccountSize_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceAttributes_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceAttributes_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceAlternateData_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceAlternateData_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceRecognition_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceRecognition_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceByHash_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceByHash_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceData_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceData_args;,
        Lcom/evernote/edam/notestore/NoteStore$updateResource_result;,
        Lcom/evernote/edam/notestore/NoteStore$updateResource_args;,
        Lcom/evernote/edam/notestore/NoteStore$unsetResourceApplicationDataEntry_result;,
        Lcom/evernote/edam/notestore/NoteStore$unsetResourceApplicationDataEntry_args;,
        Lcom/evernote/edam/notestore/NoteStore$setResourceApplicationDataEntry_result;,
        Lcom/evernote/edam/notestore/NoteStore$setResourceApplicationDataEntry_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceApplicationDataEntry_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceApplicationDataEntry_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceApplicationData_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceApplicationData_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResource_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResource_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteVersion_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteVersion_args;,
        Lcom/evernote/edam/notestore/NoteStore$listNoteVersions_result;,
        Lcom/evernote/edam/notestore/NoteStore$listNoteVersions_args;,
        Lcom/evernote/edam/notestore/NoteStore$copyNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$copyNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeInactiveNotes_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeInactiveNotes_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeNotes_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeNotes_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$deleteNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$deleteNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$updateNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$updateNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$createNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$createNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteTagNames_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteTagNames_args;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceSearchText_result;,
        Lcom/evernote/edam/notestore/NoteStore$getResourceSearchText_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteSearchText_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteSearchText_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteContent_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteContent_args;,
        Lcom/evernote/edam/notestore/NoteStore$unsetNoteApplicationDataEntry_result;,
        Lcom/evernote/edam/notestore/NoteStore$unsetNoteApplicationDataEntry_args;,
        Lcom/evernote/edam/notestore/NoteStore$setNoteApplicationDataEntry_result;,
        Lcom/evernote/edam/notestore/NoteStore$setNoteApplicationDataEntry_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteApplicationDataEntry_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteApplicationDataEntry_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteApplicationData_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNoteApplicationData_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNote_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNote_args;,
        Lcom/evernote/edam/notestore/NoteStore$findNoteCounts_result;,
        Lcom/evernote/edam/notestore/NoteStore$findNoteCounts_args;,
        Lcom/evernote/edam/notestore/NoteStore$findNotesMetadata_result;,
        Lcom/evernote/edam/notestore/NoteStore$findNotesMetadata_args;,
        Lcom/evernote/edam/notestore/NoteStore$findNoteOffset_result;,
        Lcom/evernote/edam/notestore/NoteStore$findNoteOffset_args;,
        Lcom/evernote/edam/notestore/NoteStore$findNotes_result;,
        Lcom/evernote/edam/notestore/NoteStore$findNotes_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeSearch_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeSearch_args;,
        Lcom/evernote/edam/notestore/NoteStore$updateSearch_result;,
        Lcom/evernote/edam/notestore/NoteStore$updateSearch_args;,
        Lcom/evernote/edam/notestore/NoteStore$createSearch_result;,
        Lcom/evernote/edam/notestore/NoteStore$createSearch_args;,
        Lcom/evernote/edam/notestore/NoteStore$getSearch_result;,
        Lcom/evernote/edam/notestore/NoteStore$getSearch_args;,
        Lcom/evernote/edam/notestore/NoteStore$listSearches_result;,
        Lcom/evernote/edam/notestore/NoteStore$listSearches_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeTag_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeTag_args;,
        Lcom/evernote/edam/notestore/NoteStore$untagAll_result;,
        Lcom/evernote/edam/notestore/NoteStore$untagAll_args;,
        Lcom/evernote/edam/notestore/NoteStore$updateTag_result;,
        Lcom/evernote/edam/notestore/NoteStore$updateTag_args;,
        Lcom/evernote/edam/notestore/NoteStore$createTag_result;,
        Lcom/evernote/edam/notestore/NoteStore$createTag_args;,
        Lcom/evernote/edam/notestore/NoteStore$getTag_result;,
        Lcom/evernote/edam/notestore/NoteStore$getTag_args;,
        Lcom/evernote/edam/notestore/NoteStore$listTagsByNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$listTagsByNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$listTags_result;,
        Lcom/evernote/edam/notestore/NoteStore$listTags_args;,
        Lcom/evernote/edam/notestore/NoteStore$expungeNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$expungeNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$updateNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$updateNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$createNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$createNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$getDefaultNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$getDefaultNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$getNotebook_result;,
        Lcom/evernote/edam/notestore/NoteStore$getNotebook_args;,
        Lcom/evernote/edam/notestore/NoteStore$listNotebooks_result;,
        Lcom/evernote/edam/notestore/NoteStore$listNotebooks_args;,
        Lcom/evernote/edam/notestore/NoteStore$getLinkedNotebookSyncChunk_result;,
        Lcom/evernote/edam/notestore/NoteStore$getLinkedNotebookSyncChunk_args;,
        Lcom/evernote/edam/notestore/NoteStore$getLinkedNotebookSyncState_result;,
        Lcom/evernote/edam/notestore/NoteStore$getLinkedNotebookSyncState_args;,
        Lcom/evernote/edam/notestore/NoteStore$getFilteredSyncChunk_result;,
        Lcom/evernote/edam/notestore/NoteStore$getFilteredSyncChunk_args;,
        Lcom/evernote/edam/notestore/NoteStore$getSyncChunk_result;,
        Lcom/evernote/edam/notestore/NoteStore$getSyncChunk_args;,
        Lcom/evernote/edam/notestore/NoteStore$getSyncState_result;,
        Lcom/evernote/edam/notestore/NoteStore$getSyncState_args;,
        Lcom/evernote/edam/notestore/NoteStore$Processor;,
        Lcom/evernote/edam/notestore/NoteStore$AsyncClient;,
        Lcom/evernote/edam/notestore/NoteStore$Client;,
        Lcom/evernote/edam/notestore/NoteStore$AsyncIface;,
        Lcom/evernote/edam/notestore/NoteStore$Iface;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 25
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
